import type { BuildInfo } from '../../build-info.js';

export type InstallAction = 'create' | 'same' | 'overwrite' | 'generate';

export interface InstallEntry {
  /** `<skill>/<relative path>` */
  rel: string;
  action: InstallAction;
}

export interface InstallPlan {
  entries: InstallEntry[];
  /** Hand-written files that exist at the destination with different content. */
  conflicts: string[];
}

/**
 * Pure: decides what `skills install` would do. Generated files (`references/commands.md`, …) are
 * never compared because their header carries the build date; they are always re-rendered.
 */
export function planInstall(input: {
  srcFiles: Record<string, string>;
  destFiles: Record<string, string | undefined>;
  generated: Set<string>;
}): InstallPlan {
  const entries: InstallEntry[] = [];
  const conflicts: string[] = [];
  for (const rel of Object.keys(input.srcFiles).sort()) {
    if (input.generated.has(rel)) continue;
    const existing = input.destFiles[rel];
    if (existing === undefined) entries.push({ rel, action: 'create' });
    else if (existing === input.srcFiles[rel]) entries.push({ rel, action: 'same' });
    else {
      entries.push({ rel, action: 'overwrite' });
      conflicts.push(rel);
    }
  }
  for (const rel of [...input.generated].sort()) entries.push({ rel, action: 'generate' });
  return { entries, conflicts };
}

export function generatedHeader(info: BuildInfo, date: Date): string {
  return `<!-- generated by lassi v${info.version} (${info.sha}) on ${date.toISOString().slice(0, 10)} — do not edit -->\n`;
}
