import { mkdtemp, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { nodeFs } from '@wonna/lassi-core';
import { afterEach, describe, expect, it } from 'vitest';
import { lastJsonLine, makeTestProgram } from '../../test/program.js';

const REPO_ROOT = resolve(fileURLToPath(new URL('../../../../..', import.meta.url)));

/** the tree the install must produce for each skill. */
const EXPECTED: Record<string, string[]> = {
  jira: [
    'SKILL.md',
    'references/commands.md',
    'references/errors.md',
    'references/fields.md',
    'references/formatting.md',
    'references/link-types.md',
    'references/retrieval.md',
    'references/workflows.md',
  ],
  confluence: [
    'SKILL.md',
    'references/commands.md',
    'references/errors.md',
    'references/formatting.md',
    'references/workflows.md',
  ],
};

async function walk(dir: string, prefix = ''): Promise<string[]> {
  const out: string[] = [];
  for (const name of (await readdir(dir)).sort()) {
    const path = join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if ((await stat(path)).isDirectory()) out.push(...(await walk(path, rel)));
    else out.push(rel);
  }
  return out;
}

const tmpDirs: string[] = [];
afterEach(async () => {
  await Promise.all(tmpDirs.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});

/** The real repository `skills/` tree through the real filesystem into a temporary home. */
function realProgram(home: string) {
  const t = makeTestProgram({ homedir: home, cwd: home, env: {} });
  t.deps.fs = nodeFs();
  t.deps.repoRoot = REPO_ROOT;
  return t;
}

describe('skills install (real files)', () => {
  it('installs the shipped skills with the documented skill tree, headers on generated files and short SKILL.md files', async () => {
    const home = await mkdtemp(join(tmpdir(), 'lassi-skills-'));
    tmpDirs.push(home);
    const t = realProgram(home);
    expect(await t.run(['skills', 'install'])).toBe(0);
    const root = join(home, '.agents', 'skills');
    expect((await readdir(root)).sort()).toEqual(Object.keys(EXPECTED).sort());
    for (const [skill, files] of Object.entries(EXPECTED)) {
      expect(await walk(join(root, skill))).toEqual(files);
      const skillMd = await readFile(join(root, skill, 'SKILL.md'), 'utf8');
      expect(skillMd.split('\n').length).toBeLessThanOrEqual(150);
      expect(skillMd.startsWith(`---\nname: ${skill}\ndescription: `)).toBe(true);
      // Every reference the skill points at exists next to it.
      for (const [, ref] of skillMd.matchAll(/`(references\/[a-z-]+\.md)`/g)) {
        expect(files).toContain(ref);
      }
      const commands = await readFile(join(root, skill, 'references', 'commands.md'), 'utf8');
      expect(commands.startsWith('<!-- generated by lassi v0.0.0-test (testsha) on 2026-09-04 — do not edit -->\n')).toBe(true);
      expect(commands).toContain(`lassi ${skill}`);
    }
    // fields.md renders from the alias table (no instance needed); link-types.md needs the
    // instance and says so instead of failing the install.
    const fields = await readFile(join(root, 'jira', 'references', 'fields.md'), 'utf8');
    expect(fields).toContain('<!-- generated by lassi');
    expect(fields).toContain('(no aliases configured)');
    const linkTypes = await readFile(join(root, 'jira', 'references', 'link-types.md'), 'utf8');
    expect(linkTypes).toContain('<!-- not generated: jira.url is not configured');
    expect(t.stderr()).toContain('jira/references/link-types.md: not generated');
  });

  it('re-installs unchanged files silently and refuses a modified hand-written file unless --force', async () => {
    const home = await mkdtemp(join(tmpdir(), 'lassi-skills-'));
    tmpDirs.push(home);
    const first = realProgram(home);
    expect(await first.run(['skills', 'install', '--only', 'confluence'])).toBe(0);
    const again = realProgram(home);
    expect(await again.run(['skills', 'install', '--only', 'confluence'])).toBe(0);
    expect(again.stdout()).toContain('| confluence/SKILL.md | same |');

    const target = join(home, '.agents', 'skills', 'confluence', 'references', 'workflows.md');
    await writeFile(target, '# tweaked by the team\n');
    const refused = realProgram(home);
    expect(await refused.run(['skills', 'install', '--only', 'confluence'])).toBe(5);
    expect(lastJsonLine(refused.stderr())).toMatchObject({
      code: 'validation',
      message: expect.stringContaining('confluence/references/workflows.md'),
      hint: expect.stringContaining('--force'),
    });
    expect(await readFile(target, 'utf8')).toBe('# tweaked by the team\n');

    const forced = realProgram(home);
    expect(await forced.run(['skills', 'install', '--only', 'confluence', '--force'])).toBe(0);
    expect(await readFile(target, 'utf8')).toContain('# Confluence workflows');
  });

  it('refuses --global together with --project', async () => {
    const home = await mkdtemp(join(tmpdir(), 'lassi-skills-'));
    tmpDirs.push(home);
    const t = realProgram(home);
    expect(await t.run(['skills', 'install', '--global', '--project', home])).toBe(2);
    expect(lastJsonLine(t.stderr())).toMatchObject({
      code: 'usage',
      message: '--global and --project are mutually exclusive',
    });
    expect(await walk(home)).toEqual([]);
  });
});
