import { describe, expect, it } from 'vitest';
import { lastJsonLine, makeTestProgram } from '../../test/program.js';
import { generatedHeader, planInstall } from './plan.js';

const SRC = {
  '/repo/skills/jira/SKILL.md': '---\nname: jira\n---\n# Jira via lassi\n',
  '/repo/skills/jira/references/workflows.md': '# Workflows\n',
  '/repo/skills/confluence/SKILL.md': '---\nname: confluence\n---\n# Confluence via lassi\n',
};

describe('planInstall (pure)', () => {
  it('classifies create / same / overwrite and lists conflicts, generated files always regenerate', () => {
    const plan = planInstall({
      srcFiles: { 'jira/SKILL.md': 'a', 'jira/references/workflows.md': 'w', 'jira/references/commands.md': 'stale' },
      destFiles: { 'jira/SKILL.md': 'a', 'jira/references/workflows.md': 'edited', 'jira/references/commands.md': 'old' },
      generated: new Set(['jira/references/commands.md']),
    });
    expect(plan.entries).toEqual([
      { rel: 'jira/SKILL.md', action: 'same' },
      { rel: 'jira/references/workflows.md', action: 'overwrite' },
      { rel: 'jira/references/commands.md', action: 'generate' },
    ]);
    expect(plan.conflicts).toEqual(['jira/references/workflows.md']);
  });

  it('renders the generated header', () => {
    expect(generatedHeader({ version: '0.1.0', sha: 'abc1234' }, new Date('2026-09-04T10:00:00Z'))).toBe(
      '<!-- generated by lassi v0.1.0 (abc1234) on 2026-09-04 — do not edit -->\n'
    );
  });
});

describe('skills install', () => {
  it('copies into ~/.agents/skills and renders generated references with the header', async () => {
    const t = makeTestProgram({ files: SRC });
    expect(await t.run(['skills', 'install'])).toBe(0);
    expect(await t.fs.readFile('/home/u/.agents/skills/jira/SKILL.md')).toBe(SRC['/repo/skills/jira/SKILL.md']);
    expect(await t.fs.readFile('/home/u/.agents/skills/confluence/SKILL.md')).toBe(SRC['/repo/skills/confluence/SKILL.md']);
    const commands = await t.fs.readFile('/home/u/.agents/skills/jira/references/commands.md');
    expect(commands.startsWith('<!-- generated by lassi v0.0.0-test (testsha) on 2026-09-04 — do not edit -->\n')).toBe(true);
    expect(commands).toContain('# lassi jira commands');
    expect(t.stdout()).toContain('| jira/references/commands.md | generate |');
    // Instance-specific references cannot be rendered without a configured Jira: placeholder + warning.
    const fields = await t.fs.readFile('/home/u/.agents/skills/jira/references/fields.md');
    expect(fields).toContain('(no aliases configured)');
    const linkTypes = await t.fs.readFile('/home/u/.agents/skills/jira/references/link-types.md');
    expect(linkTypes).toContain('<!-- not generated:');
    expect(t.stderr()).toContain('jira/references/link-types.md: not generated');
  });

  it('--project targets .github/skills and --only limits the skill', async () => {
    const t = makeTestProgram({ files: SRC });
    expect(await t.run(['skills', 'install', '--project', '/w/app', '--only', 'confluence'])).toBe(0);
    expect(await t.fs.exists('/w/app/.github/skills/confluence/SKILL.md')).toBe(true);
    expect(await t.fs.exists('/w/app/.github/skills/jira/SKILL.md')).toBe(false);
    expect(await t.fs.exists('/w/app/.github/skills/confluence/references/commands.md')).toBe(true);
  });

  it('resolves a relative --project against the working directory, not the process one', async () => {
    // The injected cwd is /home/u/proj; nodeFs would have resolved `sub` against process.cwd(),
    // and the dry-run preview named a path outside the workspace entirely.
    const t = makeTestProgram({ files: SRC });
    expect(await t.run(['skills', 'install', '--project', 'sub', '--only', 'jira'])).toBe(0);
    expect(await t.fs.exists('/home/u/proj/sub/.github/skills/jira/SKILL.md')).toBe(true);
  });

  it('--dry-run --json returns the shape every other write returns', async () => {
    const t = makeTestProgram({ files: SRC });
    expect(
      await t.run(['skills', 'install', '--project', 'sub', '--dry-run', '--json'])
    ).toBe(0);
    expect(JSON.parse(t.stdout())).toMatchObject({
      dryRun: true,
      method: 'PUT',
      path: 'sub/.github/skills',
      payloadLabel: 'files',
      destRoot: '/home/u/proj/sub/.github/skills',
    });
  });

  it('refuses to overwrite a modified hand-written file unless --force', async () => {
    const t = makeTestProgram({ files: { ...SRC, '/home/u/.agents/skills/jira/SKILL.md': 'my tweaks' } });
    expect(await t.run(['skills', 'install'])).toBe(5);
    expect(lastJsonLine(t.stderr())).toMatchObject({ code: 'validation', hint: expect.stringContaining('--force') });
    expect(await t.fs.readFile('/home/u/.agents/skills/jira/SKILL.md')).toBe('my tweaks');
    expect(await t.run(['skills', 'install', '--force'])).toBe(0);
    expect(await t.fs.readFile('/home/u/.agents/skills/jira/SKILL.md')).toBe(SRC['/repo/skills/jira/SKILL.md']);
  });

  it('re-installing without changes is a no-op that succeeds', async () => {
    const t = makeTestProgram({ files: SRC });
    await t.run(['skills', 'install']);
    expect(await t.run(['skills', 'install'])).toBe(0);
    expect(t.stdout()).toContain('| jira/SKILL.md | same |');
  });

  it('rejects an unknown --only and a missing skills directory', async () => {
    const t = makeTestProgram({ files: SRC });
    expect(await t.run(['skills', 'install', '--only', 'bitbucket'])).toBe(2);
    const empty = makeTestProgram();
    expect(await empty.run(['skills', 'install'])).toBe(2);
  });
});
